import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-4 relative`}>
        <nav className="bg-black w-full space-x-3 p-3 mb-3 text-white rounded font-semibold ">
          <Link className="p-1 bg-gray-400 rounded" href={'/'}>
            <span>Home </span>
          </Link>
          <Link className="p-1 bg-gray-400 rounded" href={'/reset'}>
            <span>Menu Reset</span>
          </Link>
          <Link className="p-1 bg-gray-400 rounded" href={'/keylist'}>
            <span>Add Email</span>
          </Link>
        </nav>
        {children}
        </body>
    </html>
  );
}
